# Generated by Django 4.1.4 on 2023-08-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed_variety_type',
            old_name='variey_desc',
            new_name='variety_desc',
        ),
    ]
