# Generated by Django 4.1.4 on 2023-08-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0003_category_product_sub_category_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.FileField(blank=True, default='', null=True, upload_to='category_image'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='web_panel_app.product'),
        ),
    ]
