# Generated by Django 4.2.4 on 2023-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0004_alter_category_cat_img_alter_volume_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
