# Generated by Django 4.2.4 on 2023-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0006_company_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
    ]
