# Generated by Django 4.2.4 on 2023-08-25 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0007_remove_product_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='comapny_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_panel_app.company'),
        ),
    ]
