# Generated by Django 4.2.4 on 2023-08-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0009_rename_volume_volume_product_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='web_panel_app.product'),
        ),
    ]
