# Generated by Django 4.2.4 on 2023-08-28 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0010_alter_volume_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=0, max_length=50, null=True)),
                ('payment_id', models.CharField(default=0, max_length=50, null=True)),
                ('booking_status', models.IntegerField(blank=True, default=0, null=True)),
                ('total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='web_panel_app.cart')),
                ('customer', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
