# Generated by Django 4.2.4 on 2023-09-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0013_alter_order_cart_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
