# Generated by Django 4.2.4 on 2023-09-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0014_remove_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
    ]
