# Generated by Django 4.2.4 on 2023-09-05 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0016_alter_blog_blog_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adres', models.TextField(blank=True, default='', null=True)),
                ('locality', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('custuser', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
