# Generated by Django 4.2.4 on 2023-09-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0018_alter_address_city_alter_address_locality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='issue',
            new_name='reply_msg',
        ),
    ]
