# Generated by Django 4.2.4 on 2023-09-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0019_rename_issue_contact_us_reply_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='reply_msg',
            new_name='r',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='web_panel_app.address'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='address', to='web_panel_app.cart'),
        ),
    ]
