# Generated by Django 4.2.4 on 2023-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0020_rename_reply_msg_contact_us_r_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='web_panel_app.cart'),
        ),
    ]
