# Generated by Django 4.2.4 on 2023-09-06 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0021_alter_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/product_img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_panel_app.product')),
            ],
        ),
    ]
