# Generated by Django 4.2.4 on 2023-09-13 11:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel_app', '0024_rename_r_contact_us_reply_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='test_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
